name: Tests

on:
  push:
    branches:
  pull_request:

env:
  IMAGE_NAME: rails-graphql

jobs:
  RubyTests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-18.04, macos-latest]
          ruby: [2.5, 2.6, 2.7, head]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo apt-get install libsqlite3-dev -y
      if: ${{ matrix.os  == 'ubuntu-18.04' }}
    - run: bundle install
    # - run: bundle exec rake tasks -f tasks/libgraphqlparser.rb precompile:parser
    - run: bundle exec appraisal install
    - run: bundle exec rake tasks -f tasks/libgraphqlparser.rb compile
    - run: bundle exec rake